# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=25, unique=True)),
                ('Admin_Id', models.CharField(max_length=25, unique=True)),
                ('Password', models.CharField(max_length=25, unique=True)),
                ('Confirm_PassWord', models.CharField(max_length=25, unique=True)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Contact_No', models.IntegerField(unique=True)),
                ('Password_Key', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
