# Generated by Django 3.0 on 2020-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Contact_No', models.IntegerField(unique=True)),
                ('Counsellor_Name', models.CharField(max_length=25)),
                ('Enquiry_Date', models.DateField()),
                ('Source_Name', models.CharField(max_length=25)),
                ('Enquired_For', models.CharField(max_length=25)),
                ('Course_Fee', models.IntegerField()),
                ('Assigned_To', models.CharField(max_length=25)),
                ('Degree', models.CharField(max_length=25)),
                ('YOP', models.IntegerField()),
                ('Aggregate', models.IntegerField()),
                ('Status', models.CharField(max_length=25)),
            ],
        ),
    ]
